# Generated by Django 5.0.1 on 2024-01-26 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poxymon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('hp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('speed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('move_one', models.CharField(max_length=50)),
                ('move_one_name', models.CharField(max_length=50)),
                ('move_one_power', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('move_two', models.CharField(max_length=50)),
                ('move_two_name', models.CharField(max_length=50)),
                ('move_two_power', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
