# Generated by Django 5.0.1 on 2024-01-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poxymon', '0001_initial'),
        ('poxymon_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poxymon',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poxymon_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poxymon',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='poxymon_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poxymon',
            name='move_one_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_one', to='poxymon_types.type'),
        ),
        migrations.AddField(
            model_name='poxymon',
            name='move_two_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_two', to='poxymon_types.type'),
        ),
        migrations.AddField(
            model_name='poxymon',
            name='type',
            field=models.ManyToManyField(related_name='poxymon', to='poxymon_types.type'),
        ),
    ]
