# Generated by Django 5.0.1 on 2024-01-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poxymon', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poxymon',
            name='move_one',
        ),
        migrations.RemoveField(
            model_name='poxymon',
            name='move_two',
        ),
    ]
