# Generated by Django 5.0.1 on 2024-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poxymon', '0003_remove_poxymon_move_one_remove_poxymon_move_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='poxymon',
            name='image',
            field=models.CharField(default='image'),
            preserve_default=False,
        ),
    ]
