# Generated by Django 5.0.1 on 2024-01-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poxymon', '0004_poxymon_image'),
        ('poxymon_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poxymon',
            name='type',
        ),
        migrations.AddField(
            model_name='poxymon',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='poxymon', to='poxymon_types.type'),
            preserve_default=False,
        ),
    ]
